version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://foxhole:password@db:5432/foxhole
    volumes:
      - ./public:/app/public
      - ./server:/app/server
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=foxhole
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=foxhole
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: