version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://foxhole:password@db:5432/foxhole
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - foxhole-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=foxhole
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=foxhole
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - foxhole-network

volumes:
  postgres_data:

networks:
  foxhole-network:
    driver: bridge